version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - "8123:8123" 
      - "9000:9000" 
    volumes:
       - ./data/:/var/lib/clickhouse/user_files/
       - ./init/:/docker-entrypoint-initdb.d/
    networks:
      - clickhouse-network
    ulimits:
        nofile:
          soft: 262144
          hard: 262144       
 
networks:
  clickhouse-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16